name: Java CI/CD to Azure (Windows)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package --file pom.xml

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: target/*.jar

  deploy:
    name: Deploy to Azure Web App (Windows)
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: java-Application

      - name: Rename JAR to Application.jar
        run: |
          JAR_FILE=$(ls *.jar | head -n 1)
          mv "$JAR_FILE" Application.jar

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: Application
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: Application.jar
